# image: gcc
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PLATFORM: el9

stages:
  - .pre
  - build
  - test

.configs:
  parallel:
    matrix:
      - CONFIG:
        - Debug
        - Release
        - RelWithDebInfo

.windows-platforms:
  parallel:
    matrix:
      - VS: [ v143 ]
        CONFIG:
        - Debug
        - Release
        - RelWithDebInfo

docker-image-build:
  stage: .pre
  tags:
    - docker
  script:
    - echo "$CI_REGISTRY = $CI_REGISTRY"
    - echo "$CI_REGISTRY_IMGE = $CI_REGISTRY_IMAGE"
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$PLATFORM -f Dockerfile.$PLATFORM .
    - docker push $CI_REGISTRY_IMAGE/$PLATFORM

linux-software-build:
  extends: .configs
  stage: build
  image: $CI_REGISTRY_IMAGE/$PLATFORM
  tags:
    - docker
  script:
    - echo "$CONFIG"
    - cat /etc/redhat-release
    - if [ -f /usr/bin/cmake3 ]; then export CMAKE=cmake3; else export CMAKE=cmake; fi
    - echo "$CMAKE"
    - $CMAKE --version
    - rm -rf build
    - mkdir build
    - cd build
    - scl enable gcc-toolset-14 '$CMAKE .. -G "Ninja Multi-Config" && $CMAKE --build . --config $CONFIG'
  artifacts:
    name: "dvs-$PLATFORM-$CONFIG-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./build/*

test-linux:
  extends: .configs
  stage: test
  image: $CI_REGISTRY_IMAGE/$PLATFORM
  tags:
    - docker
  needs: [ 'linux-software-build' ]
  script:
    - echo "$CONFIG"
    - ./build/tests/$CONFIG/test_dvs_command

macos-software-build:
  stage: build
  extends: .configs
  tags:
    - macos
  script:
    - echo "$CONFIG"
    - rm -rf build
    - mkdir build
    - cd build
    - if [ -f /usr/bin/cmake3 ]; then export CMAKE=cmake3; else export CMAKE=cmake; fi
    - $CMAKE --version
    - $CMAKE -G "Ninja Multi-Config" ..
    - $CMAKE --build . --config $CONFIG
  artifacts:
    name: "dvs-macos-$CONFIG-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./build/*

test-macos:
  extends: .configs
  stage: test
  tags:
    - macos
  needs: [ 'macos-software-build' ]
  script:
    - echo "$CONFIG"
    - ./build/tests/$CONFIG/test_dvs_command

windows-software-build:
  stage: build
  extends: .windows-platforms
  tags:
    - windows
  script:
    - echo "$VS"
    - echo "$CONFIG"
    - cmake --version
    - mkdir build
    - cd build
    - cmake -T $VS ..
    - cmake --build . --config $CONFIG
  artifacts:
    name: "dvs-windows-$VS-$CONFIG-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./build/*

test-windows:
  extends: .windows-platforms
  stage: test
  tags:
    - windows
  needs: [ 'windows-software-build' ]
  script:
    - echo "$CONFIG"
    - cd build\tests\$CONFIG
    - .\test_dvs_command.exe
