FROM almalinux/9-minimal

RUN microdnf update -y && \
    microdnf clean all

RUN microdnf install -y \
    epel-release

RUN microdnf install -y \
      git \
      make \
      rpmdevtools \
      tar \
      wget && \
    microdnf clean all

RUN microdnf install -y \
      gcc-toolset-14

RUN wget https://github.com/Kitware/CMake/releases/download/v3.31.1/cmake-3.31.1-linux-x86_64.sh && \
    bash cmake-*.sh --skip-license --prefix=/usr/local && \
    rm cmake*.sh

RUN wget https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip && \
    unzip ninja*.zip && \
    mv ninja /usr/local/bin && \
    rm ninja*

